import {
  CaptureAppConfig,
  CAR_COVERAGE_COMPLIANCE_ISSUES,
  ComplianceIssue,
  DEFAULT_COMPLIANCE_ISSUES,
  DeviceOrientation,
  MonkApiPermission,
  TaskName,
  VehicleType,
  ZOOM_LEVEL_COMPLIANCE_ISSUES,
} from '@monkvision/types';
import { getEnvOrThrow } from '@monkvision/common';

export const AppConfig: CaptureAppConfig = {
  enforceOrientation: DeviceOrientation.LANDSCAPE,
  defaultVehicleType: VehicleType.CUV,
  allowManualLogin: true,
  allowVehicleTypeSelection: true,
  fetchFromSearchParams: true,
  allowCreateInspection: true,
  useLiveCompliance: true,
  allowSkipRetake: true,
  enableAddDamage: false,
  createInspectionOptions: { tasks: [TaskName.DAMAGE_DETECTION, TaskName.WHEEL_ANALYSIS] },
  apiDomain: getEnvOrThrow('REACT_APP_API_DOMAIN'),
  requiredApiPermissions: [
    MonkApiPermission.TASK_COMPLIANCES,
    MonkApiPermission.TASK_DAMAGE_DETECTION,
    MonkApiPermission.TASK_DAMAGE_IMAGES_OCR,
    MonkApiPermission.TASK_WHEEL_ANALYSIS,
    MonkApiPermission.INSPECTION_CREATE,
    MonkApiPermission.INSPECTION_READ,
    MonkApiPermission.INSPECTION_UPDATE,
    MonkApiPermission.INSPECTION_WRITE,
  ],
  enableSteeringWheelPosition: false,
  sights: {
    [VehicleType.SUV]: [
      'jgc21-QIvfeg0X',
      'jgc21-__JKllz9',
      'jgc21-QwNQX0Cr',
      'jgc21-1j-oTPag',
      'jgc21-JerG7oW5',
      'jgc21-3JJvM7_B',
      'jgc21-TyJPUs8E',
      'jgc21-ezXzTRkj',
      'jgc21-ESc0HCzy',
      'jgc21-TEoi50Ff',
      'jgc21-imomJ2V0',
      'jgc21-zCrDwYWE',
      'jgc21-QIkcNhc_',
    ],
    [VehicleType.CUV]: [
      'fesc20-H1dfdfvH',
      'fesc20-Wzdtgqqz',
      'fesc20-CEGtqHkk',
      'fesc20-HYz5ziHi',
      'fesc20-r_UeXQRO',
      'fesc20-LZc7p2kK',
      'fesc20-xBFiEy-_',
      'fesc20-dfICsfSV',
      'fesc20-P470Q-jm',
      'fesc20-26n47kaO',
      'fesc20-6GPUkfYn',
      'fesc20-LTe3X2bg',
      'fesc20-GdIxD-_N',
    ],
    [VehicleType.SEDAN]: [
      'haccord-8YjMcu0D',
      'haccord-Z84erkMb',
      'haccord-EfRIciFr',
      'haccord-PGr3RzzP',
      'haccord-sorgeRJ7',
      'haccord-Jq65fyD4',
      'haccord-6kYUBv_e',
      'haccord-GdWvsqrm',
      'haccord-Qel0qUky',
      'haccord-_YnTubBA',
      'haccord-oiY_yPTR',
      'haccord-hsCc_Nct',
      'haccord-2a8VfA8m',
    ],
    [VehicleType.HATCHBACK]: [
      'ffocus18-XlfgjQb9',
      'ffocus18-lRDlWiwR',
      'ffocus18-zgLKB-Do',
      'ffocus18-FdsQDaTW',
      'ffocus18-Wo8PkcLF',
      'ffocus18-jWOq2CNN',
      'ffocus18-L2UM_68Q',
      'ffocus18-9MeSIqp7',
      'ffocus18-vFR9PKjB',
      'ffocus18-6FX31ty1',
      'ffocus18-ZXKOomlv',
      'ffocus18-43ljK5xC',
      'ffocus18-GiTxaJUq',
    ],
    [VehicleType.VAN]: [
      'ftransit18-wyXf7MTv',
      'ftransit18-IIVI_pnX',
      'front-lateral-right',
      'ftransit18-G24AdP6r',
      'ftransit18-qmLP7A-b',
      'ftransit18-FFP5b34o',
      'ftransit18-3dkU10af',
      'ftransit18-iu1Vj2Oa',
      'ftransit18-klUp8BS4',
      'ftransit18-rsXWUN8X',
      'ftransit18-5SiNC94w',
      'ftransit18-6X8IAjy0',
    ],
    [VehicleType.MINIVAN]: [
      'tsienna20-YwrRNr9n',
      'tsienna20-KHB_Cd9k',
      'tsienna20-xtDcn3GS',
      'tsienna20-uIHdpQ9y',
      'tsienna20-QIMXlb0L',
      'tsienna20--a2RmRcs',
      'tsienna20-qA3aAUUq',
      'tsienna20-1n_z8bYy',
      'tsienna20-ouPvuX-j',
      'tsienna20-4ihRwDkS',
      'tsienna20-is1tpnqR',
      'tsienna20-TI4TVvT9',
      'tsienna20-gkvZE2c7',
    ],
    [VehicleType.PICKUP]: [
      'ff150-zXbg0l3z',
      'ff150-gFp78fQO',
      'ff150-OviO2DlY',
      'ff150-_UIadfVL',
      'ff150-2WUJ179s',
      'ff150-t3KBMPeD',
      'ff150-3dkU10af',
      'ff150-xbOhu7nK',
      'ff150--xPZZd83',
      'ff150-GOx2s_9L',
      'ff150-Ttsc7q6V',
      'ff150-KgHVkQBW',
      'ff150-wO_fJ3DL',
    ],
  },
  complianceIssues: DEFAULT_COMPLIANCE_ISSUES.filter(
    (issue) =>
      ![
        ComplianceIssue.WRONG_ANGLE,
        ComplianceIssue.TOO_ZOOMED,
        ComplianceIssue.NOT_ZOOMED_ENOUGH,
      ].includes(issue),
  ),
  complianceIssuesPerSight: {
    'ff150-nF_oFvhI': DEFAULT_COMPLIANCE_ISSUES.filter(
      (issue) =>
        ![...ZOOM_LEVEL_COMPLIANCE_ISSUES, ...CAR_COVERAGE_COMPLIANCE_ISSUES].includes(issue),
    ),
  },
  palette: {
    primary: {
      xdark: '#663d00',
      dark: '#b36b00',
      base: '#ff9900',
      light: '#ffb84d',
      xlight: '#ffd699',
    },
    secondary: {
      xdark: '#082c48',
      dark: '#0e4d7e',
      base: '#146eb4',
      light: '#5b9acb',
      xlight: '#a1c5e1',
    },
  },
};
