import { Styles } from '@monkvision/types';

export const styles: Styles = {
  container: {
    // position: 'absolute',
    display: 'flex',
    alignSelf: 'stretch',
    justifyContent: 'space-between',
    flexDirection: 'column',
    backgroundColor: 'green',
    flex: '1',
  },
  containersPortrait: {
    __media: { portrait: true },
    padding: 20,
    flexDirection: 'row-reverse',
  },
  top: {
    // position: 'fixed',
    // top: '10px',
    display: 'flex',
    alignSelf: 'stretch',
    flexDirection: 'row',
    justifyContent: 'space-between',
    margin: '10px',
    zIndex: '9',
  },
  counter: {
    display: 'flex',
    color: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '6px 12px',
    borderRadius: '8px',
    backgroundColor: 'rgba(28, 28, 30, 0.64)',
    zIndex: '9',
  },
  slider: {
    // position: 'fixed',
    // bottom: '2px',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    paddingLeft: '35%',
    paddingBottom: '0%',
    overflowX: 'auto',
    overflowY: 'hidden',
    whiteSpace: 'nowrap',
    scrollbarWidth: 'none',
    maxWidth: '60vw',
    zIndex: '9',
  },
  labelButton: {
    margin: '10px',
    zIndex: '9',
  },
  sightOverlay: {
    // justifySelf: 'center',
    // position: 'fixed',
    // top: '0',
    // left: '0',
    // right: '0',
    // bottom: '0',
    // width: '100%',
    // height: '100%',
    // display: 'flex',
    zIndex: '9',
  },
};
