import { Severity } from './common';
import { MonkEntity, MonkEntityType } from './entity';
import { VehiclePart } from './part';

/**
 * Enumeration of the possible objects a severity result can be related to.
 */
export enum SeverityResultTargetType {
  /**
   * A vehcile part.
   */
  PART = 'part',
  /**
   * A damage.
   */
  DAMAGE = 'damage',
  /**
   * A comment on a severity.
   */
  COMMENT = 'comment',
}

/**
 * A severity result value containing only pricing information.
 */
export interface PricingSeverityValue {
  /**
   * The cost of the reparation.
   */
  pricing: number;
}

/**
 * The details about the operations needed to repair a damage part.
 */
export interface RepairOperation {
  /**
   * Estimation (in hours) of the labour (level 1) needed for the reparation.
   */
  t1: number;
  /**
   * Estimation (in hours) of the labour (level 2) needed for the reparation.
   */
  t2: number;
  /**
   * Estimation (in hours) of the paint job needed for the reparation.
   */
  paint: number;
  /**
   * Indicates if the part needs to be replaced or not.
   */
  replace: boolean;
}

/**
 * A severity result value generated by the system on vehicle parts.
 */
export interface PartSeverityValue {
  /**
   * The severity level of the damage.
   */
  level: Severity;
  /**
   * The cost of the reparation.
   */
  pricing?: number;
  /**
   * The operation needed to repair the part if it is damaged.
   */
  repairOperation?: RepairOperation;
}

/**
 * A severity result value manually written by the user.
 */
export interface CommentSeverityValue {
  /**
   * The comment added by the user when creating this severity result.
   */
  comment: string;
  /**
   * The severity level of the damage.
   */
  level?: Severity;
  /**
   * The cost of the reparation.
   */
  pricing?: number;
}

/**
 * Union of the possible types of severity result values.
 */
export type CustomSeverityValue = PricingSeverityValue | PartSeverityValue | CommentSeverityValue;

/**
 * Details about a severity (severity level and pricing) of an item (damage or part).
 */
export interface SeverityResult extends MonkEntity {
  /**
   * The type of the entity.
   */
  entityType: MonkEntityType.SEVERITY_RESULT;
  /**
   * The ID of the inspection associated with this severity result.
   */
  inspectionId: string;
  /**
   * The severity result value.
   */
  value?: CustomSeverityValue;
  /**
   * The ID of the item (damage or part) related to this severity result.
   */
  relatedItemId?: string;
  /**
   * The type of the item related to this severity result.
   */
  relatedItemType?: SeverityResultTargetType;
  /**
   * The name of the vehicle part related to this severity result if it is related to one.
   */
  label?: VehiclePart;
}
