export default [
    {
        id: 'e5218c58-c2f0-cc35-e54b-2e27c5d6c110',
        object_type: 'ANNOTATION_TYPE',
        created_at: '2021-11-19T13:13:48.526Z',
        deleted_at: '2021-11-19T13:13:48.526Z',
        repair_estimate: 0,
        brand: 'Renault',
        model: 'string',
        plate: 'string',
        vehicle_type: 'string',
        mileage_unit: 'km',
        mileage_value: 0,
        vin: 'NOIR_FR',
        color: 'string',
        exterior_cleanliness: 'string',
        interior_cleanliness: 'string',
        date_of_circulation: 'string',
    },
    {
        id: '3fa854df717-4562-b3fc-2c963f66afa6',
        object_type: 'ANNOTATION_TYPE',
        created_at: '2021-11-19T13:13:48.526Z',
        deleted_at: '2021-11-19T13:13:48.526Z',
        repair_estimate: 0,
        brand: 'Lambo',
        model: 'string',
        plate: 'string',
        vehicle_type: 'string',
        mileage_unit: 'km',
        mileage_value: 0,
        vin: 'BED_VAN',
        color: 'string',
        exterior_cleanliness: 'string',
        interior_cleanliness: 'string',
        date_of_circulation: 'string',
    },
    {
        id: '3fa864-5717-4562-b3fc-2c963f66afa6',
        object_type: 'ANNOTATION_TYPE',
        created_at: '2021-11-19T13:13:48.526Z',
        deleted_at: '2021-11-19T13:13:48.526Z',
        repair_estimate: 0,
        brand: 'Chevrolet',
        model: 'string',
        plate: 'string',
        vehicle_type: 'string',
        mileage_unit: 'km',
        mileage_value: 0,
        vin: 'ULISSEBDE008',
        color: 'string',
        exterior_cleanliness: 'string',
        interior_cleanliness: 'string',
        date_of_circulation: 'string',
    },
    {
        id: '3fa85f64-4-4562-b3fc-2c963f66afa6',
        object_type: 'ANNOTATION_TYPE',
        created_at: '2021-11-19T13:13:48.526Z',
        deleted_at: '2021-11-19T13:13:48.526Z',
        repair_estimate: 0,
        brand: 'Mercedez',
        model: 'string',
        plate: 'string',
        vehicle_type: 'string',
        mileage_unit: 'km',
        mileage_value: 0,
        vin: 'BED_VIN',
        color: 'string',
        exterior_cleanliness: 'string',
        interior_cleanliness: 'string',
        date_of_circulation: 'string',
    },
    {
        id: '5fa85f64-5717-d-b3fc-2c963f66afa6',
        object_type: 'ANNOTATION_TYPE',
        created_at: '2021-11-19T13:13:48.526Z',
        deleted_at: '2021-11-19T13:13:48.526Z',
        repair_estimate: 0,
        brand: 'Aston Martin',
        model: 'string',
        plate: 'string',
        vehicle_type: 'string',
        mileage_unit: 'km',
        mileage_value: 0,
        vin: 'VIN_ABC',
        color: 'string',
        exterior_cleanliness: 'string',
        interior_cleanliness: 'string',
        date_of_circulation: 'string',
    }
];
