export default {
  sights: {
    SET_PICTURE: 'SET_PICTURE',
    REMOVE_PICTURE: 'REMOVE_PICTURE',
    SET_CURRENT_SIGHT: 'SET_CURRENT_SIGHT',
    PREVIOUS_SIGHT: 'PREVIOUS_SIGHT',
    NEXT_SIGHT: 'NEXT_SIGHT',
    RESET_TOUR: 'RESET_TOUR',
  },
  uploads: {
    UPDATE_UPLOAD: 'UPDATE_UPLOAD',
    RESET_UPLOADS: 'RESET_UPLOADS',
  },
};
